name: sp-analysis
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python=3.10
    - numpy #=1.13.*
    - matplotlib #=2.1.*
    - seaborn #=0.8.1
    - plotly 
    - sqlparse
    - networkx
    - jupyter #=1.0.0
    - pandas #=0.21.*
    # DL related
     # for Jupyter
    # - rise #=5.1.*
    - jupyter_contrib_nbextensions #=0.3.3
    # for NLP
    - pip:
        # for VS code
        - pylint #==1.8.*
        - autopep8 #==1.3.*
        # misc
        - pandas_summary